#!/usr/bin/env python3
from pathlib import Path
import argparse
import re


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--buckyball-build", required=True)
    parser.add_argument("--netlist", required=True)
    parser.add_argument("--cell-model", required=True)
    parser.add_argument("--sram-root", default=None)
    parser.add_argument("--tb", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    build = Path(args.buckyball_build).resolve()
    filelist = build / "filelist.f"
    if not filelist.exists():
      raise SystemExit(f"missing buckyball filelist: {filelist}")

    skip = {
        "BuckyballAccelerator.sv",
        "ram_4x82.sv",
        "ram_4x161.sv",
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/make_mixed_filelist.py",
        f"+incdir+{build}",
    ]

    for raw in filelist.read_text().splitlines():
        item = raw.strip()
        if not item or item.startswith("//"):
            continue
        path = Path(item)
        if not path.is_absolute():
            path = build / path
        if path.name in skip:
            lines.append(f"// skipped RTL accelerator: {path}")
            continue
        lines.append(str(path.resolve()))

    # Some DPI/black-box resources are listed separately by Chipyard.
    bb_resources = build / "firrtl_black_box_resource_files.f"
    if bb_resources.exists():
        for raw in bb_resources.read_text().splitlines():
            item = raw.strip()
            if not item or item.startswith("//"):
                continue
            path = Path(item)
            if not path.is_absolute():
                path = build / path
            if path.name in skip:
                continue
            resolved = str(path.resolve())
            if resolved not in lines:
                lines.append(resolved)

    if args.sram_root:
        netlist_text = Path(args.netlist).read_text(errors="ignore")
        needed_macros = set(re.findall(r"\b(TS[0-9A-Z]+)\s+\S+\s*\(", netlist_text))
        found_macros = {}
        for path in Path(args.sram_root).resolve().rglob("VERILOG/*.v"):
            if path.name.endswith("_pwr.v"):
                continue
            text = path.read_text(errors="ignore")
            for macro in needed_macros:
                if re.search(rf"\bmodule\s+{re.escape(macro)}\b", text):
                    found_macros[macro] = path
        missing = needed_macros - set(found_macros)
        if missing:
            raise SystemExit(f"missing SRAM macro models: {', '.join(sorted(missing))}")
        for macro in sorted(found_macros):
            lines.append(str(found_macros[macro]))

    lines.extend([
        str(Path(args.cell_model).resolve()),
        str(Path(args.netlist).resolve()),
        str(Path(args.tb).resolve()),
    ])

    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
