#!/usr/bin/env python3
from pathlib import Path
import argparse
import os
import shutil
import re
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[3]
RTL_STAGE_DIR = Path(os.environ.get("RTL_STAGE_DIR", REPO_ROOT / os.environ.get("RTL_STAGE_DIR_NAME", "0_RTL")))
DEFAULT_RTL_DIR = RTL_STAGE_DIR / "RTL"


def path_is_under(path: Path, base: Path) -> bool:
    try:
        path.relative_to(base)
    except ValueError:
        return False
    return True


def resolve_listed_path(item: str, base: Path, fallback_dir: Optional[Path]) -> Path:
    path = Path(item)
    if not path.is_absolute():
        return base / path
    if path_is_under(path, base):
        return path
    if fallback_dir is not None and path_is_under(path, fallback_dir):
        return base / path.relative_to(fallback_dir)
    return base / path.name


def maybe_copy_missing(path: Path, rtl_dir: Path, fallback_dir: Optional[Path]) -> Path:
    if path.exists():
        return path
    if fallback_dir is None:
        raise FileNotFoundError(path)

    fallback = fallback_dir / path.relative_to(rtl_dir)
    if not fallback.exists():
        raise FileNotFoundError(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(fallback, path)
    print(f"copied missing RTL resource {fallback} -> {path}")
    return path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rtl-dir", default=DEFAULT_RTL_DIR)
    parser.add_argument("--fallback-build", default=None)
    parser.add_argument("--netlist", required=True)
    parser.add_argument("--cell-model", required=True)
    parser.add_argument("--sram-root", default=None)
    parser.add_argument("--tb", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    rtl_dir = Path(args.rtl_dir).resolve()
    fallback_dir = Path(args.fallback_build).resolve() if args.fallback_build else None
    filelist = rtl_dir / "filelist.f"
    if not filelist.exists():
        if fallback_dir is None:
            raise SystemExit(f"missing RTL filelist: {filelist}")
        fallback_filelist = fallback_dir / "filelist.f"
        if not fallback_filelist.exists():
            raise SystemExit(f"missing fallback filelist: {fallback_filelist}")
        rtl_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(fallback_filelist, filelist)
        print(f"copied missing RTL filelist {fallback_filelist} -> {filelist}")

    skip = {
        "BuckyballAccelerator.sv",
        "ram_4x82.sv",
        "ram_4x161.sv",
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/make_mixed_filelist.py",
        f"+incdir+{rtl_dir}",
    ]

    missing = []
    for raw in filelist.read_text().splitlines():
        item = raw.strip()
        if not item or item.startswith("//"):
            continue
        path = resolve_listed_path(item, rtl_dir, fallback_dir)
        if path.name in skip:
            lines.append(f"// skipped RTL accelerator: {path}")
            continue
        try:
            path = maybe_copy_missing(path, rtl_dir, fallback_dir)
        except FileNotFoundError:
            missing.append(path)
            continue
        lines.append(str(path.resolve()))

    if missing:
        joined = "\n  ".join(str(path) for path in missing)
        raise SystemExit(
            f"missing RTL files under {rtl_dir}. "
            "Set --fallback-build to a one-time source directory to copy them:\n  "
            + joined
        )

    # Some DPI/black-box resources are listed separately by Chipyard.
    bb_resources = rtl_dir / "firrtl_black_box_resource_files.f"
    if bb_resources.exists():
        for raw in bb_resources.read_text().splitlines():
            item = raw.strip()
            if not item or item.startswith("//"):
                continue
            path = resolve_listed_path(item, rtl_dir, fallback_dir)
            if path.name in skip:
                continue
            try:
                path = maybe_copy_missing(path, rtl_dir, fallback_dir)
            except FileNotFoundError:
                missing.append(path)
                continue
            resolved = str(path.resolve())
            if resolved not in lines:
                lines.append(resolved)
    elif fallback_dir is not None and (fallback_dir / "firrtl_black_box_resource_files.f").exists():
        fallback_bb_resources = fallback_dir / "firrtl_black_box_resource_files.f"
        shutil.copy2(fallback_bb_resources, bb_resources)
        print(f"copied missing black-box resource list {fallback_bb_resources} -> {bb_resources}")
        for raw in bb_resources.read_text().splitlines():
            item = raw.strip()
            if not item or item.startswith("//"):
                continue
            path = resolve_listed_path(item, rtl_dir, fallback_dir)
            if path.name in skip:
                continue
            try:
                path = maybe_copy_missing(path, rtl_dir, fallback_dir)
            except FileNotFoundError:
                missing.append(path)
                continue
            resolved = str(path.resolve())
            if resolved not in lines:
                lines.append(resolved)

    if missing:
        joined = "\n  ".join(str(path) for path in missing)
        raise SystemExit(
            f"missing RTL black-box resources under {rtl_dir}. "
            "Set --fallback-build to a one-time source directory to copy them:\n  "
            + joined
        )

    if args.sram_root:
        netlist_text = Path(args.netlist).read_text(errors="ignore")
        needed_macros = set(re.findall(r"\b(TS[0-9A-Z]+)\s+\S+\s*\(", netlist_text))
        found_macros = {}
        for path in Path(args.sram_root).resolve().rglob("VERILOG/*.v"):
            if path.name.endswith("_pwr.v"):
                continue
            text = path.read_text(errors="ignore")
            for macro in needed_macros:
                if re.search(rf"\bmodule\s+{re.escape(macro)}\b", text):
                    found_macros[macro] = path
        missing = needed_macros - set(found_macros)
        if missing:
            raise SystemExit(f"missing SRAM macro models: {', '.join(sorted(missing))}")
        for macro in sorted(found_macros):
            lines.append(str(found_macros[macro]))

    lines.extend([
        str(Path(args.cell_model).resolve()),
        str(Path(args.netlist).resolve()),
        str(Path(args.tb).resolve()),
    ])

    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
